seed: "usage-5min-2025"

# Khoảng thời gian sinh dữ liệu (bao gồm end)
date_range:
  start: "2025-05-01"
  end:   "2025-05-07"

paths:
  keys_csv: "data/keys/seed_keys_clean.csv"
  profile_csv: "data/raw/service_profile/service_profile_raw.parquet"   # tuỳ chọn (để cap theo băng thông)
  out_dir: "data/raw/usage"
  upload_to_minio: false

# Kiểm soát kích thước & độ phân giải
scale:
  rows_per_day_target: 1_000_000       # tổng số dòng RAW/ngày mục tiêu (5’ làm dữ liệu nhẹ hơn)
  minute_cohort_max_ratio: 0.60        # tối đa % service sinh 5’
  force_granularity: null              # "5min" | "hour" | null => auto mix

# Mô hình hành vi & phân phối (heavy variance)
model:
  daypart_profile:
    early_morning: { hours: [0,1,2,3,4,5],    dl: 0.35, ul: 0.50 }
    day:           { hours: [6,7,8,9,10,11,12,13,14,15,16,17], dl: 0.80, ul: 0.70 }
    evening:       { hours: [18,19,20,21,22,23], dl: 1.30, ul: 0.90 }
  weekend_boost: { dl: 1.10, ul: 1.05 }

  camera_presence_rate: 0.22
  camera_ul_night_boost: 1.8
  evening_stream_boost: 1.25

  # Phân phối nền (bytes) dạng lognormal (độ lệch chuẩn cao)
  ul_lognorm: { mu: 8.8, sigma: 1.10 }
  dl_lognorm: { mu: 9.3, sigma: 1.20 }

  # Heavy-tail mixture (Pareto) để tạo đuôi dày
  heavy_tail:
    prob: 0.10
    pareto_alpha: 1.7
    pareto_scale: 2.0

  # AR(1) + daily volatility tạo autocorrelation & biến động
  ar1:
    phi_range: [0.55, 0.90]
    shock_sigma: 0.65
    daily_vol_sigma: 0.35

  # Spike & Outage
  spike_per_day_prob: 0.08
  spike_multiplier_range: [2.5, 6.0]
  outage_per_day_prob: 0.03
  outage_minutes_range: [10, 90]   # sẽ quy đổi ra bucket 5’ (2..18)
  outage_hours_range:   [1, 4]     # cho hourly cohort

  # Giới hạn theo băng thông danh nghĩa (nếu có profile)
  bw_utilization_cap:
    dl_pct: 0.60
    ul_pct: 0.40

  # Jitter & thiếu điểm rời rạc
  jitter_seconds_max: 45
  random_drop_pct_per_day: 0.02

id_fields:
  session_presence_rate: 0.35
  device_mac_presence_rate: 0.55
  device_id_presence_rate: 0.35
  device_mac_per_service_max: 6
  device_id_per_service_max: 3

output:
  write_hourly: true
  write_daily:  false           # <- tắt daily aggregate
  # (giữ cấu hình dayparts nếu sau này muốn bật lại)
  dayparts: [[0,6], [6,18], [18,24]]
