seed: "subs-2025"
snapshot_month: "2025-05"

paths:
  keys_csv: "data/keys/seed_keys_clean.csv"           # bắt buộc
  crm_csv: "data/raw/crm/month=202505/crm_raw.csv"    # để backfill địa chỉ (tuỳ chọn)
  out_dir: "data/raw/subscriptions"
  upload_to_minio: true

# Danh mục gói cước + trọng số sử dụng thực tế
plans:
  catalog:
    - { plan_id: "PLN001", name: "Fiber 100", dl: 100, ul: 100, weight: 0.35 }
    - { plan_id: "PLN002", name: "Fiber 150", dl: 150, ul: 150, weight: 0.25 }
    - { plan_id: "PLN003", name: "Fiber 200", dl: 200, ul: 200, weight: 0.18 }
    - { plan_id: "PLN004", name: "Fiber 300", dl: 300, ul: 300, weight: 0.15 }
    - { plan_id: "PLN005", name: "Fiber 500", dl: 500, ul: 500, weight: 0.07 }

# Số kỳ subscription / service (1..3) — đa phần 1 kỳ
periods:
  per_service_hist: { "1": 0.80, "2": 0.16, "3": 0.04 }

dates:
  # Tỉ lệ service đang "còn hiệu lực" tại snapshot
  active_rate: 0.88
  # Độ dài hợp đồng (tháng) theo histogram
  contract_months_hist: { "6": 0.20, "12": 0.55, "18": 0.15, "24": 0.10 }
  # Khoảng trống giữa các kỳ (tháng) khi tái ký
  gap_months_hist: { "0": 0.60, "1": 0.25, "2": 0.10, "3": 0.05 }

lifecycle:
  # Xác suất & ràng buộc sự kiện trong mỗi kỳ
  upgrade_event_prob: 0.12
  upgrade_after_months_min: 3
  upgrade_after_months_max: 12
  missing_upgrade_date_prob: 0.10       # flag=1 nhưng thiếu ngày

  address_change_prob: 0.06
  address_change_after_months_min: 6
  address_change_after_months_max: 18
  missing_address_change_date_prob: 0.12

  multi_site_prob: 0.10
  multi_site_count_hist: { "1": 0.90, "2": 0.08, "3": 0.02 }

addressing:
  # Lấy địa chỉ từ CRM theo customer (nếu có file CRM)
  backfill_from_crm_rate: 0.85   # % bản ghi copy address từ CRM
  force_null_rate: 0.05          # % bản ghi vẫn để NULL address (thiếu tín hiệu)

# (tuỳ chọn) tỉ lệ thiếu trường bâng quơ khác (để mô phỏng dữ liệu thực)
missingness:
  plan_id_null_rate: 0.01        # rất nhỏ, nhưng có thể thiếu do sai log
  plan_name_null_rate: 0.008
  bandwidth_null_rate: 0.005
