seed: "profile-2025"
snapshot_month: "2025-05"

paths:
  keys_csv: "data/keys/seed_keys_clean.csv"           
  subs_csv: "data/raw/subscriptions/month=202505/subscriptions_raw.csv"  
  out_dir: "data/raw/service_profile"
  upload_to_minio: true

plans:
  catalog:
    - { plan_id: "PLN001", name: "Fiber 100", dl: 100, ul: 100, weight: 0.35 }
    - { plan_id: "PLN002", name: "Fiber 150", dl: 150, ul: 150, weight: 0.25 }
    - { plan_id: "PLN003", name: "Fiber 200", dl: 200, ul: 200, weight: 0.18 }
    - { plan_id: "PLN004", name: "Fiber 300", dl: 300, ul: 300, weight: 0.15 }
    - { plan_id: "PLN005", name: "Fiber 500", dl: 500, ul: 500, weight: 0.07 }

# ---------------- CPE catalog & behavior ----------------
device:
  models:
    - { model: "ONT-A1", weight: 0.30 }
    - { model: "ONT-B2", weight: 0.28 }
    - { model: "ONT-CX", weight: 0.22 }
    - { model: "ONT-D3", weight: 0.15 }
    - { model: "ONT-E5", weight: 0.05 }
  firmware_versions:
    ONT-A1: ["v1.0.7","v1.1.2","v1.2.0"]
    ONT-B2: ["v2.0.1","v2.1.0","v2.1.3"]
    ONT-CX: ["v3.0.0","v3.0.9"]
    ONT-D3: ["v4.0.4","v4.1.0"]
    ONT-E5: ["v5.0.0"]
  # tỉ lệ thiết bị "cũ" (flag=1), độc lập tương đối
  old_device_rate: 0.12
  # tỉ lệ có sự kiện thay CPE trước snapshot
  replacement_rate: 0.08
  # khi thay, xác suất đổi luôn model
  replacement_model_change_rate: 0.55

dates:
  # ngày lắp đặt lùi từ snapshot (ngày)
  install_days_back_min: 30
  install_days_back_max: 900
  # khi có replacement: số ngày sau install để thay (range)
  replace_days_after_install_min: 60
  replace_days_after_install_max: 700

wifi_clients:
  missing_rate: 0.10
  by_bandwidth:
    - { max_dl: 120, mean: 4,  std: 2 }
    - { max_dl: 180, mean: 6,  std: 3 }
    - { max_dl: 260, mean: 8,  std: 4 }
    - { max_dl: 350, mean: 11, std: 5 }
    - { max_dl: 600, mean: 14, std: 6 }
  default_mean: 6
  default_std: 3
  weekend_boost: 1.10   
  floor_zero: true      

missingness:
  plan_id_null_rate: 0.005
  plan_name_null_rate: 0.004
  bandwidth_null_rate: 0.000
