seed: "cdr-2025"

date_range:
  start: "2025-05-01"
  end:   "2025-05-07"

paths:
  keys_csv: "data/keys/seed_keys_clean.csv"         # bắt buộc (để biết service_id/customer_id)
  crm_csv:  "data/raw/crm/month=202505/crm_raw.csv" # tùy chọn (để lấy primary_msisdn, địa chỉ -> gán home cluster sát thực tế)
  out_dir:  "data/raw/cdr"
  upload_to_minio: false

# ---------------- Topology (cụm cell & LAC) ----------------
topology:
  mode: "synthetic"       # "synthetic" | "from_file" (nếu sau này muốn cấp sẵn cell map)
  cities:
    - name: "HaNoi"
      lac_prefix: 51001   # Location Area Code prefix (mã giả lập)
      clusters: 120       # số cụm cell (quận/phường gom nhóm)
      cells_per_cluster: [5, 18]  # mỗi cụm có 5..18 cell
    - name: "HoChiMinh"
      lac_prefix: 51002
      clusters: 160
      cells_per_cluster: [6, 22]
    - name: "DaNang"
      lac_prefix: 51003
      clusters: 40
      cells_per_cluster: [4, 12]
  # nếu có CRM với province/district, sẽ bias home cluster theo city tương ứng; nếu không, phân bổ ngẫu nhiên theo trọng số thành phố
  city_weights: { HaNoi: 0.55, HoChiMinh: 0.35, DaNang: 0.10 }

# ---------------- Persona / nhịp sống ----------------
persona_mix:
  weights:
    office_worker: 0.40
    student:       0.15
    stay_home:     0.18
    field_sales:   0.12
    shift_worker:  0.10
    night_shift:   0.05
  profiles:
    office_worker:
      leave_home_prob_weekday: 0.88
      leave_home_prob_weekend: 0.35
      work_hours: [9, 17]     # ở cụm "work" chính ban ngày
      commute_windows: { go: [7, 9], back: [17, 20] }  # giờ xuất phát (uniform)
      day_move_clusters: [1, 2]   # số cụm khác ngoài home trong ngày
      data_rate_multiplier: 1.0
    student:
      leave_home_prob_weekday: 0.80
      leave_home_prob_weekend: 0.40
      work_hours: [7, 15]
      commute_windows: { go: [6, 8], back: [15, 18] }
      day_move_clusters: [1, 2]
      data_rate_multiplier: 0.9
    stay_home:
      leave_home_prob_weekday: 0.35
      leave_home_prob_weekend: 0.45
      work_hours: [10, 16]
      commute_windows: { go: [10, 12], back: [14, 17] }
      day_move_clusters: [0, 1]
      data_rate_multiplier: 0.8
    field_sales:
      leave_home_prob_weekday: 0.95
      leave_home_prob_weekend: 0.55
      work_hours: [8, 18]
      commute_windows: { go: [7, 9], back: [18, 21] }
      day_move_clusters: [2, 6]   # đi nhiều cụm
      data_rate_multiplier: 1.2
    shift_worker:
      leave_home_prob_weekday: 0.85
      leave_home_prob_weekend: 0.60
      work_hours: [14, 22]
      commute_windows: { go: [12, 14], back: [22, 24] }
      day_move_clusters: [1, 3]
      data_rate_multiplier: 1.0
    night_shift:
      leave_home_prob_weekday: 0.70
      leave_home_prob_weekend: 0.60
      work_hours: [22, 6]  # qua đêm
      commute_windows: { go: [20, 22], back: [6, 8] }
      day_move_clusters: [1, 2]
      data_rate_multiplier: 1.1

# ---------------- Lượng dữ liệu & phân phối event ----------------
volume:
  # Poisson ổn định (NumPy) — số EVENT / 1.000 thuê bao / ngày (trước khi nhân persona)
  events_per_1k_subs: 16000      # to ra: 16k/1000/day → 9k subs ≈ 144k events/day (còn nhân persona/weekday)
  weekday_multiplier: [1.00, 1.05, 1.07, 1.00, 0.95, 0.85, 0.80]  # Mon..Sun
  # tỉ lệ event theo loại (sum≈1); data >> voice/sms
  event_type_weights: { data: 0.86, voice: 0.10, sms: 0.04 }
  # phân bố theo giờ (điểm nặng buổi tối cho data)
  hour_weights:
    "0": 0.020
    "1": 0.015
    "2": 0.012
    "3": 0.010
    "4": 0.010
    "5": 0.012
    "6": 0.018
    "7": 0.025
    "8": 0.035
    "9": 0.045
    "10": 0.050
    "11": 0.055
    "12": 0.055
    "13": 0.055
    "14": 0.055
    "15": 0.060
    "16": 0.065
    "17": 0.070
    "18": 0.075
    "19": 0.075
    "20": 0.075
    "21": 0.065
    "22": 0.050
    "23": 0.035

  # thời lượng (giây)
  duration:
    voice_lognorm: { mu: 3.3, sigma: 0.9 }  # median ~27s, heavy spread
    data_lognorm:  { mu: 4.0, sigma: 1.1 }  # session data vài chục giây → vài phút
    sms_fixed_seconds: 2
    clip: [1, 3600]                         # 1s..60ph

ids:
  imei_presence_rate: 0.92
  imei_change_prob_per_week: 0.03  # đổi máy nhẹ
  use_crm_msisdn_rate: 0.90        # 90% lấy từ CRM nếu có; 10% lấy ngẫu nhiên từ msisdn_list (nếu có)

# tỉ lệ thiếu cột / nhiễu nhẹ
missingness:
  missing_imei_if_present_prob: 0.05
  missing_lac_prob: 0.01
  missing_cell_prob: 0.005
