seed: "crm-2025"
snapshot_month: "2025-05"

paths:
  keys_csv: "data/keys/seed_keys_clean.csv"   # đường dẫn seed keys (customer/account/service)
  out_dir: "data/raw/crm"                     # thư mục output local
  upload_to_minio: true                     # true để upload
  # nếu upload_to_minio=true, cấu hình MinIO lấy từ ENV:
  # MINIO_ENDPOINT, MINIO_ACCESS_KEY, MINIO_SECRET_KEY, MINIO_SECURE, MINIO_BUCKET

demographics:
  gender_ratio:          # tỉ lệ giới tính (chuẩn hoá tự động)
    M: 0.49
    F: 0.51
  age_histogram:         # histogram tuổi (bin: weight) — tổng sẽ tự chuẩn hoá
    "18-24": 0.12
    "25-34": 0.28
    "35-44": 0.25
    "45-54": 0.18
    "55-64": 0.12
    "65-70": 0.05
  household_size_probs:  # phân phối quy mô hộ
    "1": 0.10
    "2": 0.25
    "3": 0.25
    "4": 0.25
    "5": 0.10
    "6": 0.05
  member_age_min: 1
  member_age_max: 85
  household_change_days_back_max: 365
  segments: ["mass", "value", "premium"]

# địa lý nhiều cấp có trọng số (có thể mở rộng thêm tỉnh/thành)
geography:
  cities:
    - name: "Hà Nội"
      weight: 0.5
      districts:
        - name: "Cầu Giấy"
          weight: 0.18
          wards: ["Dịch Vọng","Dịch Vọng Hậu","Yên Hòa","Quan Hoa","Nghĩa Tân","Nghĩa Đô","Mai Dịch","Trung Hòa"]
        - name: "Đống Đa"
          weight: 0.22
          wards: ["Cát Linh","Văn Miếu","Quốc Tử Giám","Láng Thượng","Láng Hạ","Ô Chợ Dừa","Khâm Thiên","Trung Liệt","Nam Đồng"]
        - name: "Hai Bà Trưng"
          weight: 0.16
          wards: ["Bạch Đằng","Bách Khoa","Bạch Mai","Đồng Nhân","Đồng Tâm","Lê Đại Hành","Minh Khai","Ngô Thì Nhậm","Phố Huế","Quỳnh Lôi"]
        - name: "Ba Đình"
          weight: 0.14
          wards: ["Điện Biên","Đội Cấn","Giảng Võ","Kim Mã","Liễu Giai","Ngọc Hà","Ngọc Khánh","Phúc Xá","Quán Thánh","Vĩnh Phúc"]
        - name: "Thanh Xuân"
          weight: 0.15
          wards: ["Hạ Đình","Khương Đình","Khương Mai","Khương Trung","Nhân Chính","Phương Liệt","Phương Mai","Thanh Xuân Bắc","Thanh Xuân Nam","Thượng Đình"]
        - name: "Hoàn Kiếm"
          weight: 0.15
          wards: ["Hàng Bạc","Hàng Buồm","Hàng Đào","Hàng Gai","Hàng Trống","Lý Thái Tổ","Tràng Tiền","Phan Chu Trinh","Cửa Đông","Cửa Nam"]
    - name: "TP. Hồ Chí Minh"
      weight: 0.4
      districts:
        - name: "Quận 1"
          weight: 0.20
          wards: ["Bến Nghé","Bến Thành","Cầu Kho","Cầu Ông Lãnh","Cô Giang","Đa Kao","Nguyễn Cư Trinh","Nguyễn Thái Bình","Phạm Ngũ Lão","Tân Định"]
        - name: "Quận 3"
          weight: 0.15
          wards: ["Võ Thị Sáu","12","13","14","5","6","7","8","9","10","11"]
        - name: "Quận 7"
          weight: 0.18
          wards: ["Tân Phong","Tân Phú","Tân Hưng","Tân Kiểng","Bình Thuận","Phú Mỹ","Phú Thuận","Tân Thuận Đông","Tân Thuận Tây"]
        - name: "TP. Thủ Đức"
          weight: 0.22
          wards: ["Linh Chiểu","Linh Tây","Linh Trung","Linh Xuân","Bình Thọ","Bình Chiểu","Trường Thọ","Hiệp Bình Chánh","Hiệp Bình Phước","Thảo Điền","An Phú"]
        - name: "Bình Thạnh"
          weight: 0.25
          wards: ["1","2","3","5","6","7","11","12","13","14","15","17","19","21","22","24","25","26","27","28"]
    - name: "Đà Nẵng"
      weight: 0.1
      districts:
        - name: "Hải Châu"
          weight: 0.45
          wards: ["Hải Châu 1","Hải Châu 2","Thạch Thang","Thanh Bình","Phước Ninh","Hòa Thuận Đông","Hòa Thuận Tây"]
        - name: "Thanh Khê"
          weight: 0.30
          wards: ["An Khê","Chính Gián","Hòa Khê","Tam Thuận","Thạc Gián","Tân Chính","Vĩnh Trung","Xuân Hà"]
        - name: "Sơn Trà"
          weight: 0.25
          wards: ["An Hải Bắc","An Hải Đông","An Hải Tây","Mân Thái","Nại Hiên Đông","Phước Mỹ","Thọ Quang"]

housing:
  types: 
    - { name: "chung_cư",  weight: 0.45 }
    - { name: "nhà_phố",   weight: 0.40 }
    - { name: "mặt_tiền",  weight: 0.08 }
    - { name: "góc",       weight: 0.05 }  # corner_house_flag=1 khi type="góc"
    - { name: "biệt_thự",  weight: 0.02 }

msisdn:
  presence_rate: 0.92            # ~8% khách không có số điện thoại
  extra_per_customer_max: 2       # số phụ 0..2

service:
  service_start_days_back_min: 30
  service_start_days_back_max: 900
